### PR TITLE
(SERVER-2017) More server simulations please

### PR DESCRIPTION
**Pull request by lindboe**
Create a new kind of pipeline that can be used to spin up a puppetserver
instance for some hands-on testing. This is basically a gatling run
without gatling or cleanup (so any desired artifacts will have to be
archived manually).

Mainly just want to see if this works since the dev workflow is a big hassle.
Still want to create a tool to simulate agent load without gatling, but
not sure that kicking it off immediately from this job is the right way
to go.

### CODE REVIEW

**Comment by haus** [comment]
@lindboe did you set the metadata for the small suts manually or via policy files (https://github.com/puppetlabs/puppetlabs-modules/blob/production/site/profile/files/razor/puppetserver-perf/tasks/puppetserver-sut-centos/7.task/kickstart.erb#L26)?

**Comment by lindboe** [comment]
Oh yes I forgot to add that in this, I only did the razor box. Thank you!

**Comment by haus** [comment]
This looks pretty reasonable. The node name is still funky, but :woman_shrugging:, the mapping seems fine.

**Comment by lindboe** [comment]
Updated

**Pull request merged**
