### PR TITLE
(PE-13023) PE 2015.3.0 Catalog Zero baseline

### PR DESCRIPTION
**Pull request by KevinCorcoran**
@haus Can you please give this a sanity check?

### CODE REVIEW

**Comment by haus** [comment]
LGTM. I have a PR open against this branch on your fork to add scenarios.

**Comment by KevinCorcoran** [comment]
@haus merged the PR against my fork.

**Comment by haus** [comment]
@KevinCorcoran sweet. i may be dropping my # of nodes to 1250, but this will be a good start. also may conflict with my PR, which also has the 1500 node csv thingy.

**Comment by haus** [comment]
:+1:

**Pull request merged**
