### PR TITLE
(maint) Add a simple script to automate part of the recording rewriting

### PR DESCRIPTION
**Pull request by haus**
Rewriting the request portions of the agent run into the various
mappings can be quite tedious, so this commit adds a script to automate
that step in the process.

### CODE REVIEW

**Comment by haus** [comment]
Updated.

**Comment by KevinCorcoran** [comment]
:+1: I used it.  It worked.  I liked it better when it had more 11's.

**Comment by nwolfe** [comment]
:+1: This is awesome!  

We should probably mention this script exists in the corresponding README for these steps (https://github.com/puppetlabs/gatling-puppet-load-test/blob/master/simulation-runner/README-GENERATING-AGENT-SIMULATIONS.md).

**Comment by haus** [comment]
@nwolfe updated

**Comment by nwolfe** [comment]
:metal:

**Pull request merged**
