### PR TITLE
(200) Add MAINTAINERS

### PR DESCRIPTION
**Pull request by cprice404**

### CODE REVIEW

**Comment by cprice404** [comment]
@haus @rlinehan are y'all ok with being included in the initial list of maintainers for this?  I know you haven't spent much time on it but I thought maybe the framework could be used for some other teams' perf testing so wanted to have a few people besides myself, Jeremy, and Joe.

@KevinCorcoran @justinstoller if either of you were interested in being on this one too, lmk.

**Comment by rlinehan** [comment]
sure

**Comment by haus** [comment]
data-shrugs

**Comment by camlow325** [comment]
👍

**Pull request merged**
