### PR TITLE
(SERVER-1465) recording for couch / perf medium catalog

### PR DESCRIPTION
**Pull request by cprice404**
These commits add a gatling scenario for PE Couch, for the 'medium' catalog from the perf control repo.

### CODE REVIEW

**Comment by camlow325** [comment]
Looks like this will need a rebase.  Not sure if there are other PRs that should still land before it's worth doing one.

**Comment by cprice404** [comment]
I think the scala-post-processing PR probably should come in before this one.

**Comment by camlow325** [comment]
I just merged #69 so I think this can be rebased now.

**Comment by cprice404** [comment]
rebased

**Comment by camlow325** [comment]
👍 Tried this out on a "dev" vm and it worked great so :shipit:

**Pull request merged**
