### PR TITLE
(maint) Install correct sbt version to avoid 2 installs

### PR DESCRIPTION
**Pull request by samwoods1**

### CODE REVIEW

**Comment by er0ck** [comment]
how does this avoid 2 installs?

what is the mkdir for?

**Comment by samwoods1** [comment]
We install sbt explicitly here, but when we execute 'sbt run' to kick off Gatling, it requires a different version and installs that version as well.
The newer version of sbt included this file and directory already, but the version Gatling requires did not, so I had to create it.

**Comment by samwoods1** [comment]
Included the above comment in the commit description.

**Comment by doug-rosser** [comment]
:+1:

**Pull request merged**
